//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfTestReadData.ReadingServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReadingServiceReference.IReadService")]
    public interface IReadService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReadService/GetHousdetails", ReplyAction="http://tempuri.org/IReadService/GetHousdetailsResponse")]
        System.Data.DataTable GetHousdetails(string _houseID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReadService/GetHousdetails", ReplyAction="http://tempuri.org/IReadService/GetHousdetailsResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetHousdetailsAsync(string _houseID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReadService/GetHouseDetails", ReplyAction="http://tempuri.org/IReadService/GetHouseDetailsResponse")]
        System.Data.DataTable GetHouseDetails();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReadService/GetHouseDetails", ReplyAction="http://tempuri.org/IReadService/GetHouseDetailsResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetHouseDetailsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReadServiceChannel : WpfTestReadData.ReadingServiceReference.IReadService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReadServiceClient : System.ServiceModel.ClientBase<WpfTestReadData.ReadingServiceReference.IReadService>, WpfTestReadData.ReadingServiceReference.IReadService {
        
        public ReadServiceClient() {
        }
        
        public ReadServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReadServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReadServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReadServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable GetHousdetails(string _houseID) {
            return base.Channel.GetHousdetails(_houseID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetHousdetailsAsync(string _houseID) {
            return base.Channel.GetHousdetailsAsync(_houseID);
        }
        
        public System.Data.DataTable GetHouseDetails() {
            return base.Channel.GetHouseDetails();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetHouseDetailsAsync() {
            return base.Channel.GetHouseDetailsAsync();
        }
    }
}
